# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\git\code_practice\python\SQlite可视化\QtSQlite.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(351, 328)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.table_lw = QtWidgets.QListWidget(self.centralwidget)
        self.table_lw.setObjectName("table_lw")
        self.horizontalLayout.addWidget(self.table_lw)
        self.data_tw = QtWidgets.QTableView(self.centralwidget)
        self.data_tw.setObjectName("data_tw")
        self.horizontalLayout.addWidget(self.data_tw)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 7)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.sql_le = QtWidgets.QLineEdit(self.centralwidget)
        self.sql_le.setObjectName("sql_le")
        self.horizontalLayout_2.addWidget(self.sql_le)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.result_te = QtWidgets.QTextEdit(self.centralwidget)
        self.result_te.setObjectName("result_te")
        self.verticalLayout.addWidget(self.result_te)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.setStretch(0, 5)
        self.verticalLayout_2.setStretch(1, 2)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 351, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.open_db_action = QtWidgets.QAction(MainWindow)
        self.open_db_action.setObjectName("open_db_action")
        self.menu.addAction(self.open_db_action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SQlite可视化工具"))
        self.label.setText(_translate("MainWindow", "输入sql语句"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.open_db_action.setText(_translate("MainWindow", "打开数据库"))
