# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\git\code_practice\python\文件管理\rar_file.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rarfile_form(object):
    def setupUi(self, rarfile_form):
        rarfile_form.setObjectName("rarfile_form")
        rarfile_form.resize(409, 408)
        rarfile_form.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.gridLayout_2 = QtWidgets.QGridLayout(rarfile_form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.open_dir_btn = QtWidgets.QPushButton(rarfile_form)
        self.open_dir_btn.setObjectName("open_dir_btn")
        self.gridLayout_2.addWidget(self.open_dir_btn, 0, 0, 1, 1)
        self.path_le = QtWidgets.QLineEdit(rarfile_form)
        self.path_le.setObjectName("path_le")
        self.gridLayout_2.addWidget(self.path_le, 0, 1, 1, 3)
        self.file_lw = QtWidgets.QListWidget(rarfile_form)
        self.file_lw.setObjectName("file_lw")
        self.gridLayout_2.addWidget(self.file_lw, 1, 0, 1, 4)
        self.groupBox = QtWidgets.QGroupBox(rarfile_form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.other_rbtn = QtWidgets.QRadioButton(self.groupBox)
        self.other_rbtn.setObjectName("other_rbtn")
        self.gridLayout.addWidget(self.other_rbtn, 1, 0, 1, 1)
        self.other_path_le = QtWidgets.QLineEdit(self.groupBox)
        self.other_path_le.setEnabled(False)
        self.other_path_le.setFocusPolicy(QtCore.Qt.NoFocus)
        self.other_path_le.setObjectName("other_path_le")
        self.gridLayout.addWidget(self.other_path_le, 1, 1, 1, 1)
        self.cur_rbtn = QtWidgets.QRadioButton(self.groupBox)
        self.cur_rbtn.setChecked(False)
        self.cur_rbtn.setObjectName("cur_rbtn")
        self.gridLayout.addWidget(self.cur_rbtn, 0, 0, 1, 1)
        self.self_rbtn = QtWidgets.QRadioButton(self.groupBox)
        self.self_rbtn.setChecked(True)
        self.self_rbtn.setObjectName("self_rbtn")
        self.gridLayout.addWidget(self.self_rbtn, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(rarfile_form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pwd_le = QtWidgets.QLineEdit(rarfile_form)
        self.pwd_le.setObjectName("pwd_le")
        self.horizontalLayout.addWidget(self.pwd_le)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(136, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 2, 1, 1)
        self.unrar_btn = QtWidgets.QPushButton(rarfile_form)
        self.unrar_btn.setObjectName("unrar_btn")
        self.gridLayout_2.addWidget(self.unrar_btn, 3, 3, 1, 1)

        self.retranslateUi(rarfile_form)
        QtCore.QMetaObject.connectSlotsByName(rarfile_form)

    def retranslateUi(self, rarfile_form):
        _translate = QtCore.QCoreApplication.translate
        rarfile_form.setWindowTitle(_translate("rarfile_form", "文件解压"))
        self.open_dir_btn.setText(_translate("rarfile_form", "打开目录"))
        self.other_rbtn.setText(_translate("rarfile_form", "解压到指定目录"))
        self.cur_rbtn.setText(_translate("rarfile_form", "解压当前目录"))
        self.self_rbtn.setText(_translate("rarfile_form", "解压到单独目录"))
        self.label.setText(_translate("rarfile_form", "密码"))
        self.unrar_btn.setText(_translate("rarfile_form", "解压"))
